name: Update README.md

on:
  push:
    branches:
      - master
  schedule:
    # UTC の 02:00 は JST だと 11:00 になる。
    - cron: '0 14 * * *'
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - run: go version

      - name: Run main.go
        run: |
          cd scripts
          go run main.go

      - name: Update README.md on a master branch
        run: |
          git add -N README.md
          if ! git diff --exit-code --quiet README.md
          then
            git config --global user.name haytok
            git config --global user.email haytok@users.noreply.github.com
            git pull
            git add README.md
            git commit -m 'update README.md'
            git push origin HEAD
          fi

      - name: Update README.md on a gh-pages branch
        run: |
          pwd
          ls
          echo git branch
          git branch
          echo ---
          git checkout -b gh-pages
          git branch
          echo ---
          git checkout master README.md
          pwd
          ls
          git status
          echo ---
          git add -N README.md
          git status
          echo ---
          if ! git diff --exit-code --quiet README.md
          then
            git config --global user.name haytok
            git config --global user.email haytok@users.noreply.github.com
            git pull
            git add README.md
            git commit -m 'update README.md'
            git push origin HEAD
          fi
