name: Update README.md

on:
  workflow_dispatch:
  schedule:
    # UTC の 02:00 は JST だと 11:00 になる。
    - cron: '0 14 * * *'
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6' # The Go version to download (if necessary) and use.
      - run: go version

      # Runs a single command using the runners shell
      - name: Run main.go
        run: |
          cd scripts
          go run main.go
