name: Update README.md

on:
  workflow_dispatch:
  schedule:
    # UTC の 02:00 は JST だと 11:00 になる。
    - cron: '0 14 * * *'
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - run: go version

      - name: Run main.go
        run: |
          cd scripts
          go run main.go

      - name: Update README.md
        run: |
          git add -N README.md
          if ! git diff --exit-code --quiet README.md
          then
            git config --global user.name haytok
            git config --global user.email haytok@users.noreply.github.com
            git pull
            git add README.md
            git commit -m 'update README.md'
            git push origin gh-pages
          fi
